name: climate
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  blurrycontainer: 1.0.2
  cupertino_icons: ^0.1.2
  geolocator: ^9.0.2
  http: ^0.12.0+2
  flutter_spinkit: ^3.1.0
  flutter_dotenv: ^5.0.2
  permission_handler: ^8.3.0

dev_dependencies:
  icon_decoration: any
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - dotenv.env

  fonts:
  - family: Spartan MB
    fonts:
    - asset: fonts/SpartanMB-Black.otf
      weight: 900